# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_userscategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userscategories',
            unique_together=set([('user', 'category')]),
        ),
    ]
